export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const RESTORE_PASSWORD = 'RESTORE_PASSWORD';
export const CLEAN_LOGIN_MESSAGE = 'CLEAN_LOGIN_MESSAGE';
export const ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT";

